### PR TITLE
added insert or replace

### PR DESCRIPTION
**Pull request by kingmesal**
Updated tests and documentation to support providing Insert and replace with an added boolean parameter to InsertOne and InsertMany

### CODE REVIEW

**Comment by Skye-31** [comment]
Thanks for the PR!
2 things:
- Could you add a changeset please? `npx changeset` in your terminal, -> semver Minor
- Do we want to allow people to set it per item in InsertMany? Could perhaps refactor the options into `{ data: Partial<T>, orReplace?: boolean }[]`. This is okay to do as v0.x has looser semver requirements, just add a note in the changeset if you decide to do this

**Comment by kingmesal** [comment]
given that it is boolean and it has a default value it is optional, and not required when called. If specifying optional without default it implies it could be undefined, but because we have a default value it is guaranteed to be at least be set to false.

**Comment by kingmesal** [comment]
I missed the other question: 

> Do we want to allow people to set it per item in InsertMany?

Generally, No. The usage here would be people looping over their own insert or insert and replace statements and batching them on their own. 

Performing some inserts mixed with some insert or replace would be similar to providing mixing deletes and updates in the same batch. Doesn't seem like a fit for the API. IMHO.

**Comment by Skye-31** [comment]
That's a fair point..
Just wondering, is the return type for each method actually correct? I seem to recall inserts returning `null` 🤔

**Comment by kingmesal** [comment]
Insert and Insert or Replace will both end up yielding a result object that looks like:
```
{
  results: null,
  duration: 34.923211097717285,
  lastRowId: 51,
  changes: 1,
  success: true,
  served_by: 'x-miniflare.db3'
}
```

**Comment by Skye-31** [comment]
We should probably update the types while doing this then. Returning `D1Result<null>` when the replace option is false, and `D1Result<{ changes: number, lastRowID: number }>` is probably best? (we could just go for unknown too?)

**Comment by kingmesal** [comment]
D1Result isn't null in any of these cases.... what I shared above is the output of both the ORM call and D1Database calls: 
```
{
  results?: T[];
  lastRowId: number | null;
  changes: number;
  duration: number;
  error?: string;
};
```
D1Result.results can be null, by its type def.

**Comment by Skye-31** [comment]
Ah makes sense, will give this a once over in the morning and then release 🙂 Thanks for the contribution!

**Pull request merged**
