### PR TITLE
Add d1 types for d1-orm lib

### PR DESCRIPTION
**Pull request by fwqaaq**
When using this library, there are many type errors due to the lack of types for D1.

### CODE REVIEW

**Comment by Skye-31** [comment]
Hey there - I've just tried a fresh worker using the library, and can't see any typing issues - do you have `@cloudflare/workers-types` in your tsconfig?

**Comment by fwqaaq** [comment]
Yeah, but my JavaScript runtime is node. Just like this:

image

**Comment by Skye-31** [comment]
Could you share a minimal repro where I can see this?

**Comment by fwqaaq** [comment]
> Could you share a minimal repro where I can see this?

I'm going to deliver the goods today. Please wait a moment.

**Comment by fwqaaq** [comment]
<https://github.com/fwqaaq/test-d1-orm-type>

I can't find d1 types when I click into `d1-orm` lib.

**Comment by Skye-31** [comment]
I see the confusion here - we're publishing the `src` directory of the project for no reason, you actually want to be looking at the `lib` directory. I've fixed this in the latest version

**Pull request closed without merging**
